import js from '@eslint/js'
import reactPlugin from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11y from 'eslint-plugin-jsx-a11y'

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  MutationObserver: 'readonly',
  AudioContext: 'readonly',
  webkitAudioContext: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  fetch: 'readonly',
  matchMedia: 'readonly',
  performance: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Image: 'readonly',
  HTMLElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  OffscreenCanvas: 'readonly',
  KeyboardEvent: 'readonly',
  Intl: 'readonly',
  process: 'readonly',
  CustomEvent: 'readonly',
  FormData: 'readonly',
  Event: 'readonly',
  Node: 'readonly',
  Element: 'readonly',
  MouseEvent: 'readonly',
  PointerEvent: 'readonly',
  TouchEvent: 'readonly',
  Blob: 'readonly',
  FileReader: 'readonly',
  Audio: 'readonly',
  GainNode: 'readonly',
  OscillatorNode: 'readonly',
  getComputedStyle: 'readonly',
  history: 'readonly',
  location: 'readonly',
  alert: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  Buffer: 'readonly',
  crypto: 'readonly',
}

export default [
  js.configs.recommended,
  {
    ignores: ['dist/**', 'node_modules/**', '**/__smoke__.mjs', '**/__ssr_smoke__.mjs'],
  },
  {
    files: ['**/*.{js,jsx,mjs}'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: browserGlobals,
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/no-unknown-property': ['error', { ignore: ['args', 'attach', 'intensity', 'position', 'rotation', 'scale', 'wireframe', 'transparent', 'emissive', 'emissiveIntensity', 'roughness', 'metalness', 'sizeAttenuation', 'depthWrite', 'dispose', 'geometry', 'material', 'object', 'frustumCulled', 'form', 'color', 'toneMapped', 'castShadow', 'receiveShadow', 'visible', 'renderOrder', 'uniforms', 'vertexShader', 'fragmentShader', 'blending', 'distance', 'decay', 'opacity', 'side', 'depthTest', 'linewidth'] }],
      'react-hooks/set-state-in-effect': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
]
