/** @type {import('tailwindcss').Config} */
import typography from '@tailwindcss/typography'

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Every colour resolves through the CSS variables in src/index.css.
        // The channel-triplet form is what preserves `/opacity` modifiers.
        'primary': 'rgb(var(--primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--primary-fixed-dim) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--on-primary-fixed-variant) / <alpha-value>)',
        'surface': 'rgb(var(--surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-bright) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-variant) / <alpha-value>)',
        'surface-tint': 'rgb(var(--surface-tint) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'background': 'rgb(var(--background) / <alpha-value>)',
        'on-background': 'rgb(var(--on-background) / <alpha-value>)',
        'outline': 'rgb(var(--outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--inverse-primary) / <alpha-value>)',
        'secondary': 'rgb(var(--secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--secondary-fixed-dim) / <alpha-value>)',
        'on-secondary': 'rgb(var(--on-secondary) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--on-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--on-secondary-fixed-variant) / <alpha-value>)',
        'tertiary': 'rgb(var(--tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--tertiary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--on-tertiary) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--on-tertiary-fixed-variant) / <alpha-value>)',
        'error': 'rgb(var(--error) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container) / <alpha-value>)',
        'on-error': 'rgb(var(--on-error) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container) / <alpha-value>)',
        'phosphor': 'rgb(var(--phosphor) / <alpha-value>)',
        // Amber, for FILLS only — as text it is ~1.5:1 on light and fails AA.
        'brand': 'rgb(var(--brand) / <alpha-value>)',
        'brand-dim': 'rgb(var(--brand-dim) / <alpha-value>)',
        'brand-tint': 'rgb(var(--brand-tint) / <alpha-value>)',
        'shadow-tint': 'rgb(var(--shadow) / <alpha-value>)',
      },
      fontFamily: {
        display: ['"Space Grotesk"', '"DM Sans"', 'sans-serif'],
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        body: ['"DM Sans"', 'sans-serif'],
        headline: ['"Space Grotesk"', '"DM Sans"', 'sans-serif'],
        label: ['"DM Mono"', 'ui-monospace', 'monospace'],
        mono: ['"DM Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        arcade: ['"Press Start 2P"', '"DM Mono"', 'monospace'],
      },
      fontSize: {
        'display-xl': ['clamp(3rem, 8vw, 7.5rem)', { lineHeight: '0.95', letterSpacing: '-0.035em' }],
        'display-lg': ['clamp(2.25rem, 5.5vw, 5rem)', { lineHeight: '1', letterSpacing: '-0.025em' }],
        'display-md': ['clamp(1.75rem, 3.8vw, 3.25rem)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-sm': ['clamp(1.375rem, 2.6vw, 2rem)', { lineHeight: '1.1', letterSpacing: '-0.015em' }],
        'eyebrow': ['0.6875rem', { lineHeight: '1', letterSpacing: '0.28em' }],
      },
      letterSpacing: {
        tightest: '-0.04em',
        eyebrow: '0.28em',
      },
      maxWidth: {
        site: '1440px',
        prose: '68ch',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        edge: 'inset 0 0 0 1px rgb(var(--outline-variant) / 0.9)',
        'edge-strong': 'inset 0 0 0 1px rgb(var(--brand) / 0.55)',
        ambient: '0 24px 64px -16px rgb(var(--shadow) / 0.18)',
        molten: '0 10px 28px -10px rgb(var(--brand) / 0.45)',
        'molten-lg': '0 18px 44px -14px rgb(var(--brand) / 0.50)',
      },
      backgroundImage: {
        molten: 'linear-gradient(135deg, rgb(var(--brand)) 0%, rgb(var(--brand-dim)) 100%)',
        'molten-hot': 'linear-gradient(135deg, rgb(var(--brand)) 0%, rgb(var(--brand-dim)) 55%, #c97f00 130%)',
        obsidian: 'linear-gradient(180deg, #ffffff 0%, rgb(var(--surface)) 60%, rgb(var(--surface-container-low)) 100%)',
      },
      zIndex: {
        nav: '50',
        progress: '55',
        grain: '60',
        cursor: '70',
        arcade: '100',
      },
      keyframes: {
        drift: {
          '0%, 100%': { transform: 'translate3d(0,0,0) scale(1)' },
          '33%': { transform: 'translate3d(4%,-3%,0) scale(1.08)' },
          '66%': { transform: 'translate3d(-3%,4%,0) scale(0.95)' },
        },
        'drift-slow': {
          '0%, 100%': { transform: 'translate3d(0,0,0) scale(1.05)' },
          '50%': { transform: 'translate3d(-5%,3%,0) scale(0.95)' },
        },
        'pulse-trail': {
          '0%': { opacity: '0', transform: 'translateY(-6px)' },
          '20%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { opacity: '0', transform: 'translateY(6px)' },
        },

        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        'marquee-reverse': { '0%': { transform: 'translateX(-50%)' }, '100%': { transform: 'translateX(0)' } },
        grain: {
          '0%, 100%': { transform: 'translate(0,0)' },
          '10%': { transform: 'translate(-5%,-10%)' },
          '20%': { transform: 'translate(-15%,5%)' },
          '30%': { transform: 'translate(7%,-25%)' },
          '40%': { transform: 'translate(-5%,25%)' },
          '50%': { transform: 'translate(-15%,10%)' },
          '60%': { transform: 'translate(15%,0%)' },
          '70%': { transform: 'translate(0%,15%)' },
          '80%': { transform: 'translate(3%,35%)' },
          '90%': { transform: 'translate(-10%,10%)' },
        },
        scanline: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100%)' } },
        flicker: { '0%, 100%': { opacity: '0.02' }, '50%': { opacity: '0.05' } },
        blink: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0' } },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 rgba(245,197,24,0)' },
          '50%': { boxShadow: '0 0 24px rgba(245,197,24,0.35)' },
        },
        'float-y': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        'spin-slow': { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        ping: { '75%, 100%': { transform: 'scale(2)', opacity: '0' } },
      },
      animation: {
        drift: 'drift 26s ease-in-out infinite',
        'drift-slow': 'drift-slow 34s ease-in-out infinite',
        'pulse-trail': 'pulse-trail 2.4s ease-in-out infinite',

        marquee: 'marquee 40s linear infinite',
        'marquee-slow': 'marquee 70s linear infinite',
        'marquee-reverse': 'marquee-reverse 38s linear infinite',
        grain: 'grain 0.4s steps(1) infinite',
        scanline: 'scanline 8s linear infinite',
        flicker: 'flicker 0.15s infinite',
        blink: 'blink 1s steps(2) infinite',
        'pulse-glow': 'pulse-glow 2.4s ease-in-out infinite',
        float: 'float-y 6s ease-in-out infinite',
        'spin-slow': 'spin-slow 30s linear infinite',
        ping: 'ping 1.6s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      typography: ({ theme }) => ({
        forge: {
          css: {
            '--tw-prose-body': 'rgb(var(--on-surface-variant))',
            '--tw-prose-headings': 'rgb(var(--on-surface))',
            '--tw-prose-lead': 'rgb(var(--on-surface))',
            '--tw-prose-links': 'rgb(var(--primary-container))',
            '--tw-prose-bold': 'rgb(var(--on-surface))',
            '--tw-prose-counters': 'rgb(var(--primary-container))',
            '--tw-prose-bullets': 'rgb(var(--outline-variant))',
            '--tw-prose-hr': 'rgb(var(--outline-variant))',
            '--tw-prose-quotes': 'rgb(var(--on-surface))',
            '--tw-prose-quote-borders': 'rgb(var(--primary-container))',
            '--tw-prose-captions': 'rgb(var(--outline))',
            '--tw-prose-code': 'rgb(var(--primary))',
            '--tw-prose-pre-code': 'rgb(var(--on-surface))',
            '--tw-prose-pre-bg': 'rgb(var(--surface-container-lowest))',
            '--tw-prose-th-borders': 'rgb(var(--outline-variant))',
            '--tw-prose-td-borders': 'rgb(var(--outline-variant))',
            maxWidth: 'none',
            'h2, h3, h4': { fontFamily: theme('fontFamily.display').join(', '), letterSpacing: '-0.02em' },
            a: { textDecoration: 'none', borderBottom: '1px solid rgb(var(--primary-container) / 0.4)' },
            'a:hover': { borderBottomColor: 'rgb(var(--primary-container))' },
            code: { fontFamily: theme('fontFamily.mono').join(', '), fontWeight: '500' },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
          },
        },
      }),
    },
  },
  plugins: [typography],
}
