/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#ffe5a0',
        'primary-container': '#f5c518',
        'primary-fixed': '#ffe08b',
        'primary-fixed-dim': '#f0c110',
        'on-primary': '#3d2f00',
        'on-primary-container': '#695200',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#584400',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#f0c110',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d1c5ac',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'outline': '#9a9078',
        'outline-variant': '#4e4633',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#745b00',
        'secondary': '#c8c6c5',
        'secondary-container': '#474746',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary': '#303030',
        'on-secondary-container': '#b7b5b4',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        'tertiary': '#e7e7e7',
        'tertiary-container': '#cbcbcb',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary': '#2f3131',
        'on-tertiary-container': '#545656',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
