export const LAST_UPDATED = 'September 2026'
export const LEGAL_EMAIL = 'legal@codecrafters.in'

export const privacySections = [
  { title: '1. Information we collect', body: `We collect information you provide directly — such as name, email address, company name, and project details submitted through our contact forms. If you accept analytics cookies, we also collect usage data (page views, session duration, referrer) through Google Analytics to understand which pages are useful. Analytics do not load at all unless you accept. We do not collect sensitive personal data without explicit consent.` },
  { title: '2. How we use your information', body: `We use collected information to: respond to your enquiries and proposals; deliver contracted services; send newsletters you've opted into; improve website performance and user experience; comply with legal obligations. We do not sell, rent, or trade your personal data to third parties.` },
  { title: '3. Legal basis for processing (GDPR)', body: `For users in the European Economic Area, we process personal data under the following legal bases: contract performance (when we've agreed to provide services); legitimate interests (improving our services, fraud prevention); consent (marketing communications and analytics). You may withdraw consent at any time.` },
  { title: '4. Cookies', body: `We use strictly necessary cookies (session management) and optional analytics cookies from Google Analytics. Analytics are disabled by default and only load after you accept them in the consent banner shown on your first visit; declining means no analytics cookies are ever set, and it does not affect site functionality. You can change your mind by clearing this site's data in your browser. The site also stores small preferences (such as arcade high scores and sound settings) in your browser's local storage; these never leave your device.` },
  { title: '5. Data retention', body: `We retain personal data only as long as necessary for the purposes collected or as required by law. Contact enquiry data is retained for 3 years. Newsletter subscriber data is retained until unsubscription. You may request deletion at any time.` },
  { title: '6. Your rights', body: `You have the right to: access your personal data; correct inaccurate data; request deletion ("right to be forgotten"); restrict or object to processing; data portability; withdraw consent at any time. To exercise these rights, contact us at ${LEGAL_EMAIL}.` },
  { title: '7. Data security', body: `We implement industry-standard security measures: TLS encryption for data in transit, encrypted storage, access controls, and regular security audits. While we take all reasonable precautions, no transmission over the internet is 100% secure.` },
  { title: '8. Third-party services', body: `We use carefully vetted third-party services including: Google Analytics (only with your consent), email delivery services, and cloud infrastructure providers (Vercel). Each is bound by data processing agreements and GDPR-compliant practices. We do not use advertising networks.` },
  { title: '9. Changes to this policy', body: `We may update this policy periodically. We'll notify you of significant changes via email (if subscribed) or a notice on this page. Continued use of our services after changes constitutes acceptance.` },
  { title: '10. Contact', body: `For privacy-related enquiries, data access requests, or complaints, contact our data controller at ${LEGAL_EMAIL}.` },
]

export const termsSections = [
  { title: '1. Acceptance of terms', body: `By accessing or using CodeCrafters services, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services. These terms apply to all visitors, clients, and users of our website and services.` },
  { title: '2. Services', body: `CodeCrafters provides AI solutions engineering, enterprise platform and ERP implementation, cloud infrastructure, security, data and design services. Specific deliverables, timelines, and pricing are defined in individual project proposals and service agreements signed between CodeCrafters and the client.` },
  { title: '3. Intellectual property', body: `Upon full payment, clients receive ownership of all custom-developed code and deliverables specific to their project. CodeCrafters retains ownership of all pre-existing tools, frameworks, libraries, and methodologies used in delivery. We reserve the right to display work in our portfolio unless a confidentiality agreement states otherwise.` },
  { title: '4. Payment terms', body: `Payment terms are defined per engagement. Project-based work typically requires a deposit before commencement. Retainer agreements are billed monthly in advance. Late payments incur a 1.5% monthly interest charge. CodeCrafters reserves the right to pause delivery on overdue accounts.` },
  { title: '5. Confidentiality', body: `CodeCrafters treats all client information as confidential. We will not disclose client data, project details, or proprietary information to third parties without written consent, except as required by law. Clients may request a mutual NDA prior to project commencement.` },
  { title: '6. Limitation of liability', body: `CodeCrafters' total liability for any claim arising from our services is limited to the amount paid for the specific engagement giving rise to the claim. We are not liable for indirect, incidental, or consequential damages including lost profits, data loss, or business interruption.` },
  { title: '7. Warranties', body: `We warrant that services will be performed professionally and in accordance with agreed specifications. We do not guarantee specific business outcomes (e.g., revenue increases). Clients are responsible for ensuring their use of delivered systems complies with applicable laws.` },
  { title: '8. Termination', body: `Either party may terminate an engagement with 30 days written notice. Upon termination, the client pays for all work completed to date. CodeCrafters will deliver all completed work product and documentation. Provisions relating to IP, confidentiality, and liability survive termination.` },
  { title: '9. Governing law', body: `These terms are governed by the laws of India. Any disputes shall be resolved through good-faith negotiation first, followed by binding arbitration in Ahmedabad, Gujarat if necessary. The prevailing party in any dispute is entitled to reasonable legal fees.` },
  { title: '10. Contact', body: `For questions about these terms or to report a concern, contact us at ${LEGAL_EMAIL}.` },
]
